
pushd .

del  Z:\nsduilib\build\duilib\Release\*.obj
del Z:\nsduilib\build\duilib\Release\*.lib
cd Z:\nsduilib\build\duilib


cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yc"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /FoZ:\nsduilib\src\duilib\stdafx.obj /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\stdafx.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIActiveX.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIActiveX.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIButton.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIButton.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UICheckBox.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UICheckBox.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UICombo.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UICombo.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIDateTime.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIDateTime.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIEdit.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIEdit.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIFlash.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIFlash.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UILabel.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UILabel.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIList.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIList.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIOption.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIOption.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIProgress.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIProgress.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIRichEdit.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIRichEdit.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIScrollBar.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIScrollBar.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UISlider.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UISlider.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIText.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIText.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UITreeView.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UITreeView.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Control\UIWebBrowser.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Control\UIWebBrowser.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIBase.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIBase.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIContainer.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIContainer.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIControl.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIControl.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIDlgBuilder.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIDlgBuilder.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIManager.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIManager.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIMarkup.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIMarkup.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Core\UIRender.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Core\UIRender.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Layout\UIChildLayout.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Layout\UIChildLayout.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Layout\UIHorizontalLayout.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Layout\UIHorizontalLayout.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Layout\UITabLayout.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Layout\UITabLayout.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Layout\UITileLayout.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Layout\UITileLayout.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Layout\UIVerticalLayout.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Layout\UIVerticalLayout.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Utils\UIDelegate.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Utils\UIDelegate.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Utils\Utils.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Utils\Utils.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yu"stdafx.h" /FpZ:\nsduilib\src\duilib\duilib.pch /Fo"Z:\nsduilib\src\duilib\Utils\WinImplBase.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Utils\WinImplBase.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"Z:\nsduilib\src\duilib\Utils\XUnzip.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TP Z:\nsduilib\src\duilib\Utils\XUnzip.cpp

cl.exe /c /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"Z:\nsduilib\src\duilib\Utils\stb_image.obj" /Fd"Z:\nsduilib\src\duilib\duilib.pdb" /Gd /TC Z:\nsduilib\src\duilib\Utils\stb_image.c

lib.exe /OUT:"Z:\nsduilib\src\duilib\duilib.lib"  /MACHINE:X86 Z:\nsduilib\src\duilib\Control\UIActiveX.obj Z:\nsduilib\src\duilib\Control\UIButton.obj Z:\nsduilib\src\duilib\Control\UICheckBox.obj  Z:\nsduilib\src\duilib\Control\UICombo.obj Z:\nsduilib\src\duilib\Control\UIDateTime.obj Z:\nsduilib\src\duilib\Control\UIEdit.obj Z:\nsduilib\src\duilib\Control\UIFlash.obj  Z:\nsduilib\src\duilib\Control\UILabel.obj Z:\nsduilib\src\duilib\Control\UIList.obj Z:\nsduilib\src\duilib\Control\UIOption.obj Z:\nsduilib\src\duilib\Control\UIProgress.obj  Z:\nsduilib\src\duilib\Control\UIRichEdit.obj Z:\nsduilib\src\duilib\Control\UIScrollBar.obj Z:\nsduilib\src\duilib\Control\UISlider.obj  Z:\nsduilib\src\duilib\Control\UIText.obj Z:\nsduilib\src\duilib\Control\UITreeView.obj Z:\nsduilib\src\duilib\Control\UIWebBrowser.obj Z:\nsduilib\src\duilib\Core\UIBase.obj  Z:\nsduilib\src\duilib\Core\UIContainer.obj Z:\nsduilib\src\duilib\Core\UIControl.obj Z:\nsduilib\src\duilib\Core\UIDlgBuilder.obj Z:\nsduilib\src\duilib\Core\UIManager.obj  Z:\nsduilib\src\duilib\Core\UIMarkup.obj Z:\nsduilib\src\duilib\Core\UIRender.obj Z:\nsduilib\src\duilib\Layout\UIChildLayout.obj  Z:\nsduilib\src\duilib\Layout\UIHorizontalLayout.obj Z:\nsduilib\src\duilib\Layout\UITabLayout.obj Z:\nsduilib\src\duilib\Layout\UITileLayout.obj  Z:\nsduilib\src\duilib\Layout\UIVerticalLayout.obj Z:\nsduilib\src\duilib\Utils\UIDelegate.obj Z:\nsduilib\src\duilib\Utils\Utils.obj  Z:\nsduilib\src\duilib\Utils\WinImplBase.obj  Z:\nsduilib\src\duilib\Utils\XUnzip.obj  Z:\nsduilib\src\duilib\Utils\stb_image.obj Z:\nsduilib\src\duilib\stdafx.obj

popd

pushd .

del Z:\nsduilib\build\nsduilib\nsduilib.dir\Release\*.obj
del Z:\nsduilib\build\nsduilib\Release\*.dll
del Z:\nsduilib\build\nsduilib\Release\*.lib
del Z:\nsduilib\build\nsduilib\Release\*.exp

cd Z:\nsduilib\build\nsduilib

cl.exe /c /IZ:\NSDUILIB\SRC\NSDUILIB\..\..\clibs\winlib /IZ:\NSDUILIB\SRC\NSDUILIB\..\DUILIB /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /D NSDUILIB_EXPORTS /D "CMAKE_INTDIR=\"Release\"" /D nsduilib_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"NSDUILIB.DIR\RELEASE\\" /Fd"NSDUILIB.DIR\RELEASE\VC140.PDB" /Gd /TP Z:\NSDUILIB\SRC\NSDUILIB\DLLMAIN.CPP

cl.exe /c /IZ:\NSDUILIB\SRC\NSDUILIB\..\..\clibs\winlib /IZ:\NSDUILIB\SRC\NSDUILIB\..\DUILIB /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /D NSDUILIB_EXPORTS /D "CMAKE_INTDIR=\"Release\"" /D nsduilib_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"NSDUILIB.DIR\RELEASE\\" /Fd"NSDUILIB.DIR\RELEASE\VC140.PDB" /Gd /TP Z:\NSDUILIB\SRC\NSDUILIB\NSDUILIB.CPP

cl.exe /c /IZ:\NSDUILIB\SRC\NSDUILIB\..\..\clibs\winlib /IZ:\NSDUILIB\SRC\NSDUILIB\..\DUILIB /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /D NSDUILIB_EXPORTS /D "CMAKE_INTDIR=\"Release\"" /D nsduilib_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"NSDUILIB.DIR\RELEASE\\" /Fd"NSDUILIB.DIR\RELEASE\VC140.PDB" /Gd /TP Z:\NSDUILIB\SRC\NSDUILIB\SKINENGINE.CPP

cl.exe /c /IZ:\NSDUILIB\SRC\NSDUILIB\..\..\clibs\winlib /IZ:\NSDUILIB\SRC\NSDUILIB\..\DUILIB /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /D NSDUILIB_EXPORTS /D "CMAKE_INTDIR=\"Release\"" /D nsduilib_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"NSDUILIB.DIR\RELEASE\\" /Fd"NSDUILIB.DIR\RELEASE\VC140.PDB" /Gd /TP Z:\NSDUILIB\SRC\NSDUILIB\STDAFX.CPP

cl.exe /c /IZ:\NSDUILIB\SRC\NSDUILIB\..\..\clibs\winlib /IZ:\NSDUILIB\SRC\NSDUILIB\..\DUILIB /IZ:\nsduilib\src\duilib\..\..\clibs\winlib /IZ:\nsduilib\src\duilib  /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D UNICODE /D _UNICODE /D UILIB_STATIC /D NSDUILIB_EXPORTS /D "CMAKE_INTDIR=\"Release\"" /D nsduilib_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"NSDUILIB.DIR\RELEASE\\" /Fd"NSDUILIB.DIR\RELEASE\VC140.PDB" /Gd /TC Z:\NSDUILIB\SRC\NSDUILIB\PLUGINAPI.C

link.exe /ERRORREPORT:PROMPT /OUT:"Z:\nsduilib\build\nsduilib\Release\nsduilib.dll" /INCREMENTAL:NO Z:\nsduilib\src\nsduilib\..\..\duilib\duilib.lib Shlwapi.lib Z:\nsduilib\clibs\staticlib\winlib.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /manifestinput:D:\vs2015\VC\Include\Manifest\dpiaware.manifest /PDB:"Z:/nsduilib/build/nsduilib/Release/nsduilib.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"Z:/nsduilib/build/nsduilib/Release/nsduilib.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /DLL nsduilib.dir\Release\dllmain.obj nsduilib.dir\Release\nsduilib.obj nsduilib.dir\Release\pluginapi.obj nsduilib.dir\Release\SkinEngine.obj nsduilib.dir\Release\StdAfx.obj

popd